### ISSUE TITLE
Why do u use Rsocket

### ISSUE THREAD

**Issue by HelloTo4x** [Montura/graal-rsocket-ios#1]
Hi,i am reading your code, why do you use Rsocket instead of other protocols like gRPC or socket, websocket... What is your use case which you use Rsocket, thank you so much

**Comment by Montura** [comment]
Hi, I'm a newbie in network protocols, so the best answer for your question is an article about [differences between gRPC and RSocket](https://medium.com/netifi/differences-between-grpc-and-rsocket-e736c954e60#:~:text=gRPC%20is%20an%20RPC%20framework,sits%20on%20top%20of%20RSocket).

So, I'm just experimenting and that's it.

**Comment by HelloTo4x** [comment]
thank u
